### CSE 344 : Computer Vision Homework 18
**Name :** Arka sarkar <br>
**Roll Number :** 2018222 <br>

In [1]:
import numpy as np
from scipy import signal
x=np.array([[12 ,14 ,15 ,17],[34 ,56 ,73 ,32],[ 67 ,43 ,31 ,21],[32 ,31 ,43 ,56]])
w=np.array([[-1 , 0],[0,-1]])
b=0.3
dy= np.array([[-2, 3, 4],[-1, 5, 3],[2, 3, 4]])

#### Compute updated 'b' and 'w' in the current layer. [0.5 marks]

In [2]:
# Calculation db
db = np.sum(dy)
print("db : ", db)

db :  21


In [3]:
#Calculation dw
dw = signal.convolve2d(x,dy,mode = "valid")

print("dw : \n", dw)

dw : 
 [[764 859]
 [970 911]]


In [4]:
#updating w and b
learning_rate = 0.1 

w_up = w - learning_rate*dw
b_up = b - learning_rate*db

print("updated w :\n", w_up)
print("updated b :\n", b_up)


updated w :
 [[-77.4 -85.9]
 [-97.  -92.1]]
updated b :
 -1.8


#### Compute 'dy' for the next layer (in the backward direction) [0.5 marks]

In [5]:
#calculating dx
dy_0 = np.zeros((dy.shape[0]+2,dy.shape[1]+2 )) #padded dy
dy_0[1:-1,1:-1] = dy
w_prime = np.rot90(w,2)
dx = signal.convolve2d(dy_0,w_prime, mode = "valid")

print("dx : \n", dx)


dx : 
 [[ 2. -3. -4.  0.]
 [ 1. -3. -6. -4.]
 [-2. -2. -9. -3.]
 [ 0. -2. -3. -4.]]


In [6]:
x_up = x - learning_rate*dx
print("x updated:\n", x_up)

x updated:
 [[11.8 14.3 15.4 17. ]
 [33.9 56.3 73.6 32.4]
 [67.2 43.2 31.9 21.3]
 [32.  31.2 43.3 56.4]]


In [7]:
dy_new = signal.convolve2d(x_up, w_up, mode = "valid")
print("dy for the next layer : \n", dy_new)

dy for the next layer : 
 [[ -9743.51 -13343.64 -11897.34]
 [-17699.45 -18504.37 -14310.19]
 [-15543.2  -13104.52 -13088.92]]
